title: Graphics and Compute Freedom Day (GCFD)
description: Graphics and Compute Freedom Day is a worldwide celebration of open standards, technologies, software, and hardware in graphics and compute.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
